version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - ./app:/app
    ports:
      - "80:3000"

  adminer:
    image: adminer
    ports:
        - 8080:8080

  db:
    image: postgres
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1mudar123
    ports:
      - "5432:5432"
